PACKAGE_NAME="macb-xdp"
PACKAGE_VERSION="6.18.35+xdp1"

BUILT_MODULE_NAME[0]="macb_xdp"
BUILT_MODULE_LOCATION[0]="macb"
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"

MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/macb modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/macb clean"
