PACKAGE_NAME="r8169-xdp"
PACKAGE_VERSION="6.18.35+xdp1"

BUILT_MODULE_NAME[0]="r8169_xdp"
BUILT_MODULE_LOCATION[0]="r8169"
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"

MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/r8169 modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/r8169 clean"
